###
curl http://localhost:3000

### DID Resolver microservice
curl http://localhost:3000/resolve/did:key:zDnaenKBwm6DDPgRgaiTwyW8Ny18bSbJ1efnd58ZCQPmCdjmH

###
curl http://localhost:3000/status-checks/list/1 -X GET 

###
curl --verbose http://localhost:3000/trusted-issuers/did:key:xxxxxxxxxx -X GET 


###
curl http://localhost:3000/status-checks/list/20 -X GET 

###
curl http://localhost:3000/status-lists/list/entries/20/status -X PUT \
    -H 'Content-Type: application/json' \
    -d '{"status": "revoked"}'

###
curl http://localhost:3000/status-lists/list/entries/20/status -X PUT \
    -H 'Content-Type: application/json' \
    -d '{"status": "valid"}'    

###
curl http://localhost:3000/status-lists/list/entries/20/status -X PUT \
    -H 'Content-Type: application/json' \
    -d '{"status": "xxxxx"}'    

###
curl http://localhost:3000/status-lists/register -X POST \
    -H 'Content-Type: application/json' \
    -d '{"credentials": 1000}'    