openapi: 3.0.0
paths:
  /resolve/{did}:
    get:
      description: このエンドポイントはDIDを解決します。入力としてDIDを受け取ります。
      operationId: ResolverController_handleGetUniversalResol
      parameters:
        - name: did
          required: true
          in: path
          description: 解決するDIDを指定する
          schema:
            example: did:key:z6MknCCLeeHBUaHu4aHSVLDCYQW9gjVJ7a63FpMvtuVMy53T
            type: string
        - name: Accept
          required: false
          in: header
          description: 処理識別子
          examples:
            application/did+json:
              value: applicaiton/json
              description: DIDドキュメントのメディアタイプ（JSON）
            application/did+ld+json:
              value: applicaiton/did+ld+json
              description: DIDドキュメントのメディアタイプ（JSON-LD）。
            application/ld+json;profile="https://w3id.org/did-resolution":
              value: application/ld+json;profile="https://w3id.org/did-resolution"
              description: DID解決結果のメディアタイプ (JSON-LD).
          schema:
            type: string
        - name: X-Correlation-ID
          in: header
          description: 処理識別子
          required: false
          schema:
            type: string
      responses:
        '200':
          content:
            application/did+json:
              schema:
                type: object
                description: The DID document (JSON representation).
                example:
                  id: did:indy:sovrin:WRfXPg8dantKVubE3HX8pw
                  verificationMethod:
                    - id: did:indy:sovrin:WRfXPg8dantKVubE3HX8pw#key-1
                      type: Ed25519VerificationKey2018
                      publicKeyBase58: H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV
            application/did+ld+json:
              schema:
                type: object
                description: The DID document (JSON-LD representation).
                example:
                  '@context': https://www.w3.org/ns/did/v1
                  id: did:indy:sovrin:WRfXPg8dantKVubE3HX8pw
                  verificationMethod:
                    - id: did:indy:sovrin:WRfXPg8dantKVubE3HX8pw#key-1
                      type: Ed25519VerificationKey2018
                      publicKeyBase58: H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV
            application/ld+json;profile="https://w3id.org/did-resolution":
              schema:
                description: The DID resolution result.
                type: object
                properties:
                  didDocument:
                    type: object
                  didResolutionMetadata:
                    type: object
                    additionalProperties: {}
                  didDocumentMetadata:
                    type: object
                    additionalProperties: {}
          description: DIDの解決に成功した
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '406':
          description: サポートされていない表現です。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '410':
          description: 正常に解決されましたが、DIDは無効化されています。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '501':
          description: DIDメソッドはサポートされていません
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: Resolver DID
      tags:
        - Resolver
info:
  title: VC Analyzer System DID Resolver API
  description: API documentation for the VC Analyzer System management plane.
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    ErrorServiceMetadata:
      type: object
      properties:
        serviceName:
          type: string
          description: サービス名
        version:
          type: string
          description: サービスバージョン
        timestamp:
          type: string
          description: 応答時間
        processingTimeMillis:
          type: number
          description: 処理時間
        correlationId:
          type: string
          description: 処理識別子
      required:
        - serviceName
        - version
        - timestamp
        - processingTimeMillis
        - correlationId
    ErrorMainResponse:
      type: object
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
        details:
          description: エラー詳細
          type: array
          items:
            type: object
      required:
        - code
        - message
        - details
    ErrorResponse:
      type: object
      properties:
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ErrorServiceMetadata'
        error:
          description: エラー情報
          allOf:
            - $ref: '#/components/schemas/ErrorMainResponse'
      required:
        - serviceMetadata
        - error
