openapi: 3.0.0
paths:
  /trusted-issuers:
    post:
      description: このエンドポイントは、発行者を登録します。入力としてDIDを受け取ります。
      operationId: TrustedListController_hundleCreateIssuer
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectDidRegistrationDto'
      responses:
        '200':
          description: 発行者に登録に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 認証は成功したが、この操作を実行する権限がない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - gateway-jwt: []
      summary: Resolver DID
      tags: &ref_0
        - APIs that do not require authentication
    get:
      description: このエンドポイントはVC発行者情報をリストで返します。
      operationId: TrustedListController_hundleGetIssuers
      parameters: []
      responses:
        '200':
          description: リストの取得に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 受け取った、scjectDidのデータは存在しているが、proofの検証に失敗した。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - gateway-jwt: []
      summary: VC発行者の検証
      tags: *ref_0
  /trusted-issuers/{subjectDid}:
    patch:
      description: このエンドポイントはDIDを解決します。入力としてDID、有効期限（オプション）を受け取ります。
      operationId: TrustedListController_hundleUpdateIssuer
      parameters:
        - name: subjectDid
          required: true
          in: path
          description: 発行者のDIDを指定する
          schema:
            example: did:key:z6Mkiq1TQyWPezBTGoqNvcq9b6azWMyn6HwQmbjo5LLpai68
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubjectDidUpdateDto'
      responses:
        '200':
          description: 発行者の情報Dの更新に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 認証は成功したが、この操作を実行する権限がない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 受け取った、subjectDidのデータは存在しているが、proofの検証に失敗した。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - gateway-jwt: []
      summary: 発行者の情報を更新する。
      tags: *ref_0
    delete:
      description: このエンドポイントは登録済みの発行者を削除します。入力としてDIDを受け取ります。
      operationId: TrustedListController_hundleDeleteIssuer
      parameters:
        - name: subjectDid
          required: true
          in: path
          description: 削除するDIDを指定する
          schema:
            example: did:key:z6Mkiq1TQyWPezBTGoqNvcq9b6azWMyn6HwQmbjo5LLpai68
            type: string
      responses:
        '200':
          description: 発行者の削除に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 認証は成功したが、この操作を実行する権限がない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - gateway-jwt: []
      summary: 発行者の削除
      tags: *ref_0
    get:
      description: このエンドポイントはVC発行者を検証します。入力としてDIDを受け取ります。
      operationId: TrustedListController_hundleGetIssuer
      parameters:
        - name: subjectDid
          required: true
          in: path
          description: 検証するDIDを指定する
          schema:
            example: did:key:z6Mkiq1TQyWPezBTGoqNvcq9b6azWMyn6HwQmbjo5LLpai68
            type: string
      responses:
        '200':
          description: VC発行者の検証に成功した。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrustedListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 受け取った、scjectDidのデータは存在しているが、検証に失敗した。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: VC発行者の検証
      tags: *ref_0
info:
  title: VC Analyzer System Trusted List API
  description: API documentation for the VC Analyzer System management plane.
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    SubjectDidRegistrationDto:
      type: object
      properties:
        subjectDid:
          type: string
          description: 登録者のDID
          example: did:key:z6Mkiq1TQyWPezBTGoqNvcq9b6azWMyn6HwQmbjo5LLpai68
        policy:
          type: object
          description: 未サポート
      required:
        - subjectDid
    TrustedIssuerResponse:
      type: object
      properties:
        trustedIssuer:
          type: string
          description: 発行者のDID 削除処理以外の場合
          example: did:key:z6Mkiq1TQyWPezBTGoqNvcq9b6azWMyn6HwQmbjo5LLpai68
        deletedTrustedIssuer:
          type: string
          description: 発行者のDID 削除処理の場合
          example: did:key:z6Mkiq1TQyWPezBTGoqNvcq9b6azWMyn6HwQmbjo5LLpai68
        status:
          type: string
          description: 状態コード（VC発行者の検証時以外は付加されない）
          examples:
            - value: no-trusted
              description: 信頼されていない
            - value: trusted
              description: 信頼されている
        validUntil:
          type: string
          description: 有効期限 (VC発行者の検証時以外は付加されない）
          example: '2025-05-10T12:01:04.828Z'
        metadata:
          type: object
          description: メタ情報
        message:
          type: string
          description: 成功メッセージ
    ServiceMetadataDto:
      type: object
      properties:
        serviceName:
          type: string
          description: サービス名
        version:
          type: string
          description: サービスバージョン
        timestamp:
          type: string
          description: 応答時間
        processingTimeMillis:
          type: number
          description: 処理時間
        verifableCredentialUrl:
          type: string
          description: IPFS URL(オプション）
        fetchedCid:
          type: string
          description: IPFS CID（オプション）
        createdCid:
          type: string
          description: IPFS CID（オプション）
      required:
        - serviceName
        - version
        - timestamp
        - processingTimeMillis
    TrustedListSuccessResponse:
      type: object
      properties:
        payload:
          description: ペイロード
          allOf:
            - $ref: '#/components/schemas/TrustedIssuerResponse'
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ServiceMetadataDto'
      required:
        - payload
        - serviceMetadata
    ErrorServiceMetadata:
      type: object
      properties:
        serviceName:
          type: string
          description: サービス名
        version:
          type: string
          description: サービスバージョン
        timestamp:
          type: string
          description: 応答時間
        processingTimeMillis:
          type: number
          description: 処理時間
        correlationId:
          type: string
          description: 処理識別子
      required:
        - serviceName
        - version
        - timestamp
        - processingTimeMillis
        - correlationId
    ErrorMainResponse:
      type: object
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
        details:
          description: エラー詳細
          type: array
          items:
            type: object
      required:
        - code
        - message
        - details
    ErrorResponse:
      type: object
      properties:
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ErrorServiceMetadata'
        error:
          description: エラー情報
          allOf:
            - $ref: '#/components/schemas/ErrorMainResponse'
      required:
        - serviceMetadata
        - error
    SubjectDidUpdateDto:
      type: object
      properties:
        validUntil:
          type: string
          description: ISO 8601フォーマット
          example: '2024-11-03T01:23:56.789Z'
        policy:
          type: object
