openapi: 3.0.0
paths:
  /status-lists:
    post:
      description: このエンドポイントはステータスリストを作成します。入力としてリストのサイズを受け取ります。
      operationId: StatusListController_hundleCreateList
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusListCreateDto'
      responses:
        '200':
          description: ステータスリストの作成に成功した。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 認証は成功したが、この操作を実行する権限がない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - gateway-jwt: []
      summary: ステータスリストの作成
      tags: &ref_0
        - Bitstring Status List
  /status-lists/{listId}/status/{index}:
    get:
      description: このエンドポイントはステータスリストの状態を取得します。入力としてlistId, indexを受け取ります。
      operationId: StatusListController_handleStatusCheks
      parameters:
        - name: listId
          required: true
          in: path
          description: リストIDを指定する
          schema:
            example: d8290d62-813d-44a9-98d3-fd27c85f729b
            type: string
        - name: index
          required: true
          in: path
          description: indexを指定する
          schema:
            example: '123'
            type: number
      responses:
        '200':
          description: ステータスリストの状態取得に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 受け取った、listIdのデータは存在しているが、検証に失敗した。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: ステータスリストの状態取得
      tags: *ref_0
    patch:
      description: このエンドポイントはステータスをrevokedに更新します。入力としてlistId,indexを受け取ります。
      operationId: StatusListController_handleUpdateStatus
      parameters:
        - name: listId
          required: true
          in: path
          description: listIdを指定する
          schema:
            example: d8290d62-813d-44a9-98d3-fd27c85f729b
            type: string
        - name: index
          required: true
          in: path
          description: indexを指定する
          schema:
            example: '123'
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusListUpdateDto'
      responses:
        '200':
          description: ステータスの更新に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusListSuccessResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 認証は成功したが、この操作を実行する権限がない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 受け取った、listIdのデータは存在しているが、検証に失敗した。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - gateway-jwt: []
      summary: ステータスの更新
      tags: *ref_0
info:
  title: VC Analyzer System Status List API
  description: API documentation for the VC Analyzer System management plane.
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    StatusListCreateDto:
      type: object
      properties:
        size:
          type: number
          example: '1000'
        statusPurpose:
          type: string
          example: revocation
          description: 省略時は、`revocation`
        bits:
          type: number
          example: 0
          description: >-
            `{specName}` が "bitstring" の場合で、statusPurposeがmessageの時のみ必須 (1, 2,
            3)。
        bitMapping:
          type: object
          example: 1
          description: '`ビット値の文字列とステータス文字列の対応マップ`'
      required:
        - size
        - bitMapping
    StatusListResponse:
      type: object
      properties:
        listId:
          type: string
          description: 作成、更新または確認対象のリスト識別子
        index:
          type: number
          description: 確認対象のインデックス
        status:
          type: string
          description: 指定インデックスの現在のステータス文字列
        bitValue:
          type: number
          description: 指定インデックスの現在のビット値
        newBitValue:
          type: number
          description: 更新されたインデックスのビット値
        newStatus:
          type: string
          description: 更新後の新しいステータス文字列
        message:
          type: string
          description: 成功メッセージ
      required:
        - listId
    ServiceMetadataDto:
      type: object
      properties:
        serviceName:
          type: string
          description: サービス名
        version:
          type: string
          description: サービスバージョン
        timestamp:
          type: string
          description: 応答時間
        processingTimeMillis:
          type: number
          description: 処理時間
        verifableCredentialUrl:
          type: string
          description: IPFS URL(オプション）
        fetchedCid:
          type: string
          description: IPFS CID（オプション）
        createdCid:
          type: string
          description: IPFS CID（オプション）
      required:
        - serviceName
        - version
        - timestamp
        - processingTimeMillis
    StatusListSuccessResponse:
      type: object
      properties:
        payload:
          description: ペイロード
          allOf:
            - $ref: '#/components/schemas/StatusListResponse'
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ServiceMetadataDto'
      required:
        - payload
    ErrorServiceMetadata:
      type: object
      properties:
        serviceName:
          type: string
          description: サービス名
        version:
          type: string
          description: サービスバージョン
        timestamp:
          type: string
          description: 応答時間
        processingTimeMillis:
          type: number
          description: 処理時間
        correlationId:
          type: string
          description: 処理識別子
      required:
        - serviceName
        - version
        - timestamp
        - processingTimeMillis
        - correlationId
    ErrorMainResponse:
      type: object
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
        details:
          description: エラー詳細
          type: array
          items:
            type: object
      required:
        - code
        - message
        - details
    ErrorResponse:
      type: object
      properties:
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ErrorServiceMetadata'
        error:
          description: エラー情報
          allOf:
            - $ref: '#/components/schemas/ErrorMainResponse'
      required:
        - serviceMetadata
        - error
    StatusListUpdateDto:
      type: object
      properties:
        status:
          type: string
          example: revoked
      required:
        - status
