openapi: 3.0.0
paths:
  /status-lists/register:
    post:
      description: このエンドポイントはDIDを解決します。入力としてDIDを受け取ります。
      operationId: ProtectedStatusListController_hundleRegistrationStatus
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusListCreateDto'
      responses:
        '200':
          description: DIDの解決に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 認証は成功したが、この操作を実行する権限がない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
        '422':
          description: データの検証に失敗した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security: &ref_0
        - gateway-jwt: []
      summary: Resolver DID
      tags: &ref_1
        - ProtectedStatusList
  /status-lists/{listId}/entries/{index}/status:
    put:
      description: このエンドポイントはDIDを解決します。入力としてDIDを受け取ります。
      operationId: ProtectedStatusListController_handleUpdateStatus
      parameters:
        - name: listId
          required: true
          in: path
          description: 解決するDIDを指定する
          schema:
            example: urn:d8290d62-813d-44a9-98d3-fd27c85f729b
            type: string
        - name: index
          required: true
          in: path
          description: 解決するDIDを指定する
          schema:
            example: '123'
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusListUpdateDto'
      responses:
        '200':
          description: DIDの解決に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrPutResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 認証は成功したが、この操作を実行する権限がない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: データの検証に失敗した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security: *ref_0
      summary: Resolver DID
      tags: *ref_1
  /status-checks/{listId}/{index}:
    get:
      description: このエンドポイントはDIDを解決します。入力としてDIDを受け取ります。
      operationId: PublicStatusListController_handleStatusCheks
      parameters:
        - name: listId
          required: true
          in: path
          description: 解決するDIDを指定する
          schema:
            example: urn:d8290d62-813d-44a9-98d3-fd27c85f729b
            type: string
        - name: index
          required: true
          in: path
          description: 解決するDIDを指定する
          schema:
            example: '123'
            type: number
      responses:
        '200':
          description: DIDの解決に成功した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrPutResponse'
        '400':
          description: リクエストが無効
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: データが存在しない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: データの検証に失敗した
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: サーバー内部エラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      summary: Resolver DID
      tags:
        - PublicStatusList
info:
  title: VC Analyzer System Status List API
  description: API documentation for the VC Analyzer System management plane.
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    StatusListCreateDto:
      type: object
      properties:
        credentials:
          type: number
          example: '1000'
      required:
        - credentials
    AddStatusIssuer:
      type: object
      properties:
        listId:
          type: string
          description: リストID
          example: urn:d8290d62-813d-44a9-98d3-fd27c85f729b
      required:
        - listId
    AddPayloadLoad:
      type: object
      properties:
        statusIssuer:
          description: 発行者のステータスリスト情報
          allOf:
            - $ref: '#/components/schemas/AddStatusIssuer'
        status:
          type: string
          description: 状態コード
          examples:
            - value: revoked
              description: 失効
            - value: valid
              description: 正常
      required:
        - statusIssuer
        - status
    ServiceMetadata:
      type: object
      properties:
        serviceName:
          type: string
          description: サービス名
        version:
          type: string
          description: サービスバージョン
        timestamp:
          type: string
          description: 応答時間
        processingTimeMillis:
          type: string
          description: 処理時間
        ipfsGatewayUrl:
          type: string
          description: IPFS URL
        fetchedCid:
          type: string
          description: IPFS CID
      required:
        - serviceName
        - version
        - timestamp
        - processingTimeMillis
        - ipfsGatewayUrl
        - fetchedCid
    AddResponse:
      type: object
      properties:
        payload:
          description: ペイロード
          allOf:
            - $ref: '#/components/schemas/AddPayloadLoad'
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ServiceMetadata'
      required:
        - payload
    ErrorMainResponse:
      type: object
      properties:
        message:
          type: string
          description: エラーメッセージ
        code:
          type: string
          description: エラーコード
        details:
          description: エラー詳細
          type: array
          items:
            type: object
      required:
        - message
        - code
    ErrorServiceMetadata:
      type: object
      properties:
        serviceName:
          type: string
          description: サービス名
        version:
          type: string
          description: サービスバージョン
        timestamp:
          type: string
          description: 応答時間
        processingTimeMillis:
          type: string
          description: 処理時間
        correlationId:
          type: string
          description: 処理識別子
      required:
        - serviceName
        - version
        - timestamp
        - processingTimeMillis
        - correlationId
    ErrorResponse:
      type: object
      properties:
        error:
          description: サービスエラー
          allOf:
            - $ref: '#/components/schemas/ErrorMainResponse'
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ErrorServiceMetadata'
      required:
        - error
    StatusListUpdateDto:
      type: object
      properties:
        status:
          type: string
          example: revoked
      required:
        - status
    GetOrPutStatusIssuer:
      type: object
      properties:
        listId:
          type: string
          description: リストID
          example: urn:d8290d62-813d-44a9-98d3-fd27c85f729b
        index:
          type: string
          description: インデックス
          example: '123'
      required:
        - listId
        - index
    GetOrPutPayloadLoad:
      type: object
      properties:
        statusIssuer:
          description: 発行者のステータスリスト情報
          allOf:
            - $ref: '#/components/schemas/GetOrPutStatusIssuer'
        status:
          type: string
          description: 状態コード
          examples:
            - value: revoked
              description: 失効
            - value: valid
              description: 正常
      required:
        - statusIssuer
        - status
    GetOrPutResponse:
      type: object
      properties:
        payload:
          description: ペイロード
          allOf:
            - $ref: '#/components/schemas/GetOrPutPayloadLoad'
        serviceMetadata:
          description: サービスメタ情報
          allOf:
            - $ref: '#/components/schemas/ServiceMetadata'
      required:
        - payload
