// src/common/messages/errorMessages.ts

// メッセージに埋め込む値の型を定義すると、より型安全になります（オプション）
export const ResponseErrorCode = {
  post: {
    400: [
      'ERR_CREATE_INVALID_SIZE',
      'ERR_CREATE_INVALID_STATUS_PURPOSE',
      'ERR_CREATE_INVALID_BITS',
      'ERR_CREATE_INVALID_BIT_MAPPING',
      'ERR_CREATE_INVALID_PAYLOAD',
    ],
    401: ['ERR_AUTHENTICATION_FAILED'],
    403: ['ERR_PERMISSION_DENIED'],
    404: ['ERR_UPDATE_UNSUPPORTED_SPEC'],
    409: ['ERR_CREATE_ID_COLLISION'],
    500: [
      'ERR_PERSISTENCE_ERROR',
      'ERR_IPFS_ERROR',
      'ERR_SIGNING_FAILED',
      'ERR_INTERNAL_ERROR',
    ],
  },
  patch: {
    400: [
      'ERR_UPDATE_INVALID_PAYLOAD',
      'ERR_UPDATE_MISSING_STATUS',
      'ERR_UPDATE_INVALID_STATUS_STRING',
      'ERR_UPDATE_UNMAPPED_STATUS',
      'ERR_UPDATE_INDEX_OUT_OF_BOUNDS',
    ],
    401: ['ERR_AUTHENTICATION_FAILED'],
    403: ['ERR_PERMISSION_DENIED'],
    404: ['ERR_UPDATE_UNSUPPORTED_SPEC', 'ERR_LIST_NOT_FOUND'],
    409: ['ERR_CREATE_ID_COLLISION'],
    422: ['ERR_VERIFICATION_INVALID'],
    500: [
      'ERR_PERSISTENCE_ERROR',
      'ERR_IPFS_ERROR',
      'ERR_SIGNING_FAILED',
      'ERR_INTERNAL_ERROR',
      'ERR_BITSTRING_OPERATION_FAILED',
    ],
  },
  get: {
    400: [
      'ERR_UPDATE_INVALID_PAYLOAD',
      'ERR_UPDATE_MISSING_STATUS',
      'ERR_UPDATE_INVALID_STATUS_STRING',
      'ERR_UPDATE_UNMAPPED_STATUS',
      'ERR_GET_INDEX_OUT_OF_BOUNDS ',
    ],
    401: ['ERR_AUTHENTICATION_FAILED'],
    403: ['ERR_PERMISSION_DENIED'],
    404: ['ERR_UPDATE_UNSUPPORTED_SPEC', 'ERR_LIST_NOT_FOUND'],
    409: ['ERR_CREATE_ID_COLLISION'],
    422: ['ERR_VERIFICATION_INVALID'],
    500: [
      'ERR_PERSISTENCE_ERROR',
      'ERR_IPFS_ERROR',
      'ERR_SIGNING_FAILED',
      'ERR_INTERNAL_ERROR',
      'ERR_BITSTRING_OPERATION_FAILED',
    ],
  },
};
